### ISSUE TITLE
Contact list: Using zero after +46 makes number not match tinktime database (see attachement)

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#105]
![img_3838](https://cloud.githubusercontent.com/assets/10393619/8735690/0920ca9a-2c13-11e5-8a3b-0534b3b466e5.PNG)

**Comment by MonicaSylvander** [comment]
![img_3839](https://cloud.githubusercontent.com/assets/10393619/8735725/5524eb92-2c13-11e5-9b7a-e78f8bbe13da.PNG)

**Comment by MonicaSylvander** [comment]
![img_3840](https://cloud.githubusercontent.com/assets/10393619/8735738/61ffaa00-2c13-11e5-993d-1848619faa6b.PNG)

**Comment by MonicaSylvander** [comment]
![img_3841](https://cloud.githubusercontent.com/assets/10393619/8735744/69a0895a-2c13-11e5-98a7-6722c0390358.PNG)

**Comment by shikarkhane** [comment]
Should the first zero after country code always be removed? Is this a valid assumption for all the countries? 
I don't know.

**Comment by MonicaSylvander** [comment]
After some research: There is a common practice of omitting the leading zero. So yes, we can assume this for all countries.

**Comment by shikarkhane** [comment]
I did exactly what you did by adding a zero. But when i called that number, it said the number is not in use.
So if a user has such a number in his contact list, he/she cannot call that number ( checked on android).

Wikipedia says that if you use country code, you should remove the first zero. If you don't do that you cannot call that number anyways.

So I am not sure if this stands as a bug.

**Comment by MonicaSylvander** [comment]
In Iphone you can call the number with the zero added - it automatically puts it in () - Fredrik has a few phone numbers like that in his phone book and it works for him to call them.

**Comment by shikarkhane** [comment]
This is a special case. And i cannot solve this because ...
Lets say i have a swedish phone number stored in my phone as 070 5438947. The i move to USA. I get a american phone number +1 303 899 5656. Now when i use tinktime app, it will make swedish number as +1 70 543 8947. Which is wrong. But then i change the Swedish number in phone contacts to +46 070 543 8947. 
Now my authenticated phone number on tinktime app is american i.e. +1 country code. I have no way to figure out which position digit of +46 070 543 8947 should i check and remove if zero.

????

**Comment by shikarkhane** [comment]
This is fixed and works as follows:
1. On registration, we omit leading zero. +46070.... becomes +4670
2. a phone contact stored as 070... becomes +4670... if +46 is the dial code of registered user.
3. a phone contact stored as +46070... is changed to +4670
