### ISSUE TITLE
Social media links in tinkometer

### ISSUE THREAD

**Issue by MonicaSylvander** [shikarkhane/tt#157]

**Comment by shikarkhane** [comment]
This needs to be brainstormed a bit.

If we simply share Tinkometer screen and someone in friends list on fb sees it, it won't impress him/her.

We should come up with 2 infographic pages, which we build using the time-split info which we have. 
Also these pages which we share should say "tinktime", "time is a gift, share it" etc etc

Right now, i will make it so that clicking on share buttons simply shares tinktime.com url on Facebook with our slogan "time is a gift, share it"
